### ISSUE TITLE
Question about the USB hub speed?

### ISSUE THREAD

**Issue by X-Lemon-X** [Hugoyhu/SL2.1A-Type-C-Hub#2]
I have a question about this design did you manage to get High speed (480Mb) or just  full speed (12MHz)

**Comment by Hugoyhu** [comment]
Sorry for the delayed response! 

Testing this with a USB3.0 capable SSD, I am able to achieve 300Mbps read/write. The design is capable of up to USB 2.0 speeds.

**Comment by X-Lemon-X** [comment]
Thank you
